name: Shell Script Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup ShellCheck (Bash)
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: ShellCheck Scan (Bash)
        shell: bash
        run: |
          find . -type f -name "*.sh" -print0 | xargs -0 shellcheck
